import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Player from "@/components/shared/Player";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="min-h-[70vh] max-w-[90rem] py-28 mx-5 xl:mx-auto">
          {children}
        </div>
        <Player />
      </body>
    </html>
  );
}
